# Introducción a NumPy

In [28]:
import numpy as np

n_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(f"{n_array} -> type {type(n_array)}")

[[1 2 3]
 [4 5 6]] -> type <class 'numpy.ndarray'>


## ndarray vs Lista de Python (benchmark)

- NumPy es significativamente más rápido que las listas de Python para operaciones numéricas. La razón principal es que NumPy usa memoria contigua y operaciones vectorizadas en C, evitando el overhead del intérprete de Python para cada elemento.

In [29]:
import numpy as np
import time

size = 1_000_000

# list 
items_list = list(range(size))
start = time.time()
result_list = [x ** 2 for x in items_list]
end = time.time()
result_time_list = end - start


# nrray

array = np.arange(size)
start = time.time()
result_items_np = [x**2 for x in array]
result_time_np = time.time() - start

print("Times for list against narray")
print(f"\ttime list: {result_time_list:.4f}")
print(f"\ttime np: {result_time_np:.4f}")
print(f"\tnumpy is {result_time_list/result_time_np:.2f}x times faster")


Times for list against narray
	time list: 0.0451
	time np: 0.0531
	numpy is 0.85x times faster


## Funciones de Creación

In [30]:
print("=== np.zeros - Array de ceros ===")
print(np.zeros((3, 4)))

print("=== np.ones - Array de unos ===")
print(np.ones((2, 3)))

print("=== np.empty - Array sin inicializar (valores arbitrarios) ===")
print(np.empty((2, 2)))

print("=== np.arange - Secuencia de números ===")
print(np.arange(0, 10, 2))

print("=== np.linspace - Números equiespaciados ===")
print(np.linspace(0, 1, 5))

print("=== np.eye - Matriz identidad ===")
print(np.eye(3, 4))

print("=== np.random - Números aleatorios ===")
print("rand (uniforme [0,1)):\n", np.random.rand(2, 3))
print("randn (normal estándar):\n", np.random.randn(2, 3))
print("randint (enteros [0,10)):\n", np.random.randint(0, 10, (2, 3)))

print("=== np.full - Array con valor constante ===")
print(np.full((2, 3), 7))

print("=== np.identity - Matriz identidad cuadrada ===")
print(np.identity(4))

=== np.zeros - Array de ceros ===
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
=== np.ones - Array de unos ===
[[1. 1. 1.]
 [1. 1. 1.]]
=== np.empty - Array sin inicializar (valores arbitrarios) ===
[[1. 1.]
 [1. 1.]]
=== np.arange - Secuencia de números ===
[0 2 4 6 8]
=== np.linspace - Números equiespaciados ===
[0.   0.25 0.5  0.75 1.  ]
=== np.eye - Matriz identidad ===
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
=== np.random - Números aleatorios ===
rand (uniforme [0,1)):
 [[0.91193402 0.53076416 0.04735822]
 [0.63939565 0.91935381 0.4310236 ]]
randn (normal estándar):
 [[-0.68669546 -0.1096228  -0.01599868]
 [-0.60550033  2.04070454 -0.27474012]]
randint (enteros [0,10)):
 [[0 9 0]
 [5 0 6]]
=== np.full - Array con valor constante ===
[[7 7 7]
 [7 7 7]]
=== np.identity - Matriz identidad cuadrada ===
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Atributos del ndarray
- Cada ndarray tiene atributos que describen su estructura. Conocerlos es esencial para depurar código y entender qué datos estás manejando.

In [31]:
import numpy as np

# Crear una matriz de ejemplo
datos = np.array([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0],
                  [7.0, 8.0, 9.0]])

print("shape:", datos.shape)   # (3, 3) — filas x columnas
print("dtype:", datos.dtype)   # float64
print("ndim:", datos.ndim)     # 2 — número de dimensiones
print("size:", datos.size)     # 9 — total de elementos
print("nbytes:", datos.nbytes) # 72 — bytes en memoria

# Cambiar dtype
enteros = datos.astype(np.int32)
print("\ndtype después de astype:", enteros.dtype)

# Más atributos útiles
print("\n--- Más atributos ---")
print("itemsize:", datos.itemsize, "bytes por elemento")
print("strides:", datos.strides, "(bytes para avanzar en cada dimensión)")
print("flags:")
print(datos.flags)
print("T (transpose):\n", datos.T)

# Array 1D para más ejemplos
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n--- Array 1D ---")
print("arr_1d:", arr_1d)
print("arr_1d.cumsum():", arr_1d.cumsum())  # Suma acumulativa
print("arr_1d.cumprod():", arr_1d.cumprod())  # Producto acumulativo

# Atributos de transposición
print("\n--- Transposición ---")
print("datos.transpose():")
print(datos.transpose())

# reshape - cambiar forma sin alterar datos
print("\n--- Reshape ---")
flat = np.arange(12)
print("flat:", flat)
print("flat.reshape(3, 4):")
print(flat.reshape(3, 4))

# ravel - aplanar array
print("\n--- Aplanar ---")
mat = np.ones((2, 3))
print("mat.ravel():", mat.ravel())

shape: (3, 3)
dtype: float64
ndim: 2
size: 9
nbytes: 72

dtype después de astype: int32

--- Más atributos ---
itemsize: 8 bytes por elemento
strides: (24, 8) (bytes para avanzar en cada dimensión)
flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

T (transpose):
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

--- Array 1D ---
arr_1d: [1 2 3 4 5]
arr_1d.cumsum(): [ 1  3  6 10 15]
arr_1d.cumprod(): [  1   2   6  24 120]

--- Transposición ---
datos.transpose():
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

--- Reshape ---
flat: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flat.reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

--- Aplanar ---
mat.ravel(): [1. 1. 1. 1. 1. 1.]


## Tips y Mejores Prácticas

| Tip | Descripción |
|------|-------------|
| 💡 **Reproducibilidad** | Usa `np.random.seed()` al inicio para garantizar resultados reproducibles |
| 💡 **linspace vs arange** | `np.linspace` para puntos equidistantes (gráficas). `np.arange` para paso fijo |
| ⚠️ **Homogeneidad** | Los arrays son homogéneos: mixt int y float → todo se convierte a float |
| ℹ️ **Inicialización** | `np.zeros`/`np.ones` son más eficientes que `append()` en loops |
| 💡 **Memoria** | Usa `array.nbytes` para estimar uso. `float32` ahorra memoria si no necesitas alta precisión |

## Errores Comunes

### 1. Listas anidadas con tamaños diferentes

**Código incorrecto:**
```python
np.array([[1, 2], [3, 4, 5]])  # ❌ Filas de distinto tamaño
```

**¿Por qué?** NumPy no puede crear un array 2D rectangular si las filas tienen diferente longitud.

**Solución:** Asegúrate de que todas las filas tengan la misma longitud.

### 2. `np.arange` con pasos float

**Código problemático:**
```python
np.arange(0, 1, 0.1)  # ⚠️ Puede dar 10 u 11 elementos según el sistema
```

**¿Por qué?** Los floats tienen precisión limitada.

**Solución:** Usa `np.linspace(0, 1, 10)` para exactamente N puntos.

### 3. `np.zeros` crea float64 por defecto

**Código incorrecto:**
```python
np.zeros((3, 3))  # ❌ Da 0.0 (float), no 0 (int)
```

**¿Por qué?** El dtype por defecto es float64.

**Solución:**
```python
np.zeros((3, 3), dtype=int)       # ✅ Enteros
np.zeros((3, 3), dtype=np.int32) # ✅ Enteros de 32 bits
```

### 4. Usar `.shape` como función

**Código incorrecto:**
```python
array.shape()  # ❌ TypeError: 'tuple' object is not callable
```

**¿Por qué?** `shape` es un atributo, no un método.

**Solución:**
```python
array.shape  # ✅ Sin paréntesis
# Atributos: .shape, .dtype, .ndim, .size, .nbytes, .itemsize
```