# Operaciones Matemáticas
Álgebra lineal, estadísticas, aleatorios

In [42]:
import numpy as np

a = np.array(list(range(10, 51, 10)))
b = np.array(list(range(1, 6, 1)))

print(a+b)

[11 22 33 44 55]


In [43]:
# Ventas mensuales: 6 meses x 4 regiones
np.random.seed(1)
ventas = np.random.randint(50, 200, size=(6, 4))
meses = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun']
regiones = ['Norte', 'Sur', 'Este', 'Oeste']

print(ventas)

print("\nMinimal statistics")
for i, region in enumerate(regiones):
    sells = ventas[:, i]
    print(f"reg: {region}, mean: {sells.mean()}, total: {sells.sum()}, min-max: {sells.min()} - {sells.max()}")
    
print("\nBy month")
sells = ventas.sum(axis=1)
max_sells_i = np.argmax(sells)
print(sells, f"month: {meses[max_sells_i]}, max: {sells[max_sells_i]}")

print("\nGrow month by month")
grow = np.diff(sells)
print(sells, grow)

[[ 87 190 122 187]
 [183 129 194 179]
 [121 184  75  70]
 [151 196 189 192]
 [100 118 146 136]
 [191 187  57 113]]

Minimal statistics
reg: Norte, mean: 138.83333333333334, total: 833, min-max: 87 - 191
reg: Sur, mean: 167.33333333333334, total: 1004, min-max: 118 - 196
reg: Este, mean: 130.5, total: 783, min-max: 57 - 194
reg: Oeste, mean: 146.16666666666666, total: 877, min-max: 70 - 192

By month
[586 685 450 728 500 548] month: Abr, max: 728

Grow month by month
[586 685 450 728 500 548] [  99 -235  278 -228   48]


In [44]:
def add_vectors(left, right):
    result = []
    for i in range(0, len(left)):
        result.append(left[i] + right[i])
        
    return result

print(add_vectors([1, 2, 3], [4, 5, 6]))

[5, 7, 9]


In [45]:
def inner_values(values):
    return values[1:-1]

print(inner_values([10, 20, 30, 40]))

[20, 30]
